# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Unity Wiki

plugins:
  - search
  - macros

theme:
  logo: assets/images/logo.png
  name: material
  palette: 
    - scheme: slate  # Dark mode by default
      primary: indigo
      accent: blue
  favicon: assets/images/logo.png
  features:
    - navigation.tabs
    - search.suggest
    - content.code.copy
    - content.tabs.link
  icon:
    admonition:
      abstract: material/clipboard-text
      bug: material/shield-bug
      danger: material/lightning-bolt-circle
      example: material/test-tube
      failure: material/close
      info: material/information
      note: material/note
      question: material/help-circle
      quote: material/format-quote-close
      success: material/check
      tip: material/fire
      warning: material/alert

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

nav:
  - Home: index.md
  - Recruitment: recruitment.md
  - Raid Info:
      - Info: raid-info.md
      - Guides:
          - Molten Core: guides/raids/molten-core.md
          - Blackwing Lair: guides/raids/blackwing-lair.md
          - Temple of Ahn'Qiraj: guides/raids/temple-of-ahnqiraj.md
          - Naxxramas: guides/raids/naxxramas.md